include: package:flutter_lints/flutter.yaml

linter:
  rules:
    non_constant_identifier_names: false
    sort_child_properties_last: false
    avoid_print: false
    prefer_const_constructors: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
